spring.application.name=taskmanagement

spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=09453111179
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=3f8b2c9d4e1a7f6b0c5d2e9a4b7f1c8d3e6a9b2c5f8e1d4a7b0c3f6e9d2a5b8

#86400000 is 24 hours in milliseconds.
jwt.expiration=86400000
