services:
  postgres:
    image: postgres:16
    container_name: taskmanagement-db
    environment:
      POSTGRES_DB: taskdb         # name of the database to create
      POSTGRES_USER: admin       # username
      POSTGRES_PASSWORD: password   # password
    ports:
      - "5432:5432"            # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: